### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by jbernardis** [DNS-OARC/dnsperf#118]
Trying to build from source on Centos system.   All dependencies installed, but I get the following error:

dns.o: In function `name_fromstring':
/root/dnsperf/dnsperf-2.3.4/src/dns.c:200: undefined reference to `isc_buffer_constinit'

Not sure how to proceed

**Comment by jelu** [comment]
This is because of the BIND development libraries dependency (bind-devel).

I'd recommend that you use our CentOS / EPEL package repositories instead: https://copr.fedorainfracloud.org/coprs/g/dnsoarc/dnsperf/ .

If you don't want to do that then you can try again with bind-devel installed or wait a few weeks and we will have a version without this dependency.

If none of this works then I need CentOS version and full output of configure and make.

**Comment by jbernardis** [comment]
Thanks for the reply Jerry.  I am trying to see if corporate will allow us
to use your repository.  BTW - we already have the
bind-devel package installed:

*Package 32:bind-devel-9.8.2-0.68.rc1.el6_10.8.x86_64 already installed and
latest version*


Perhaps we should just wait the few weeks you mentioned.

**Comment by jelu** [comment]
Hmm, are you running CentOS 6?

We only really support (build, test and packages) the latest major version
of CentOS, which is 8 now, and 6 just went EOL.

**Comment by jbernardis** [comment]
Yes.  This is not one of my usual servers, but it is running centos 6.
I'll see if I can get them to modernize.

**Comment by jelu** [comment]
If you upgrade to CentOS 7 or 8 then the current release will build as we do that ourselves.

The bind-devel that is in CentOS 6 is too old.

And later, if you don't want to use our packages then you can easily create your own using the [`rpm/dnsperf.spec`](https://github.com/DNS-OARC/dnsperf/blob/v2.3.4/rpm/dnsperf.spec) SPEC file and `rpmbuild`.
