### ISSUE TITLE
Option in resperf.c

### ISSUE THREAD

**Issue by Javier-Ruiz-at-Amaris** [DNS-OARC/dnsperf#155]
Hi, is there a way to have the EDNS [option](https://github.com/DNS-OARC/dnsperf/blob/8b0d7b0d26225be63d5214f7b2df9d32ae649eb8/src/dnsperf.c#L459
) also in `resperf`?
Thanks!

I have been using the -Z option from an old Nominum [version](https://gitlab.isc.org/isc-projects/dnsperf/-/blob/master/resperf.c#L283), but to send the record would be nice in resperf.

**Comment by jelu** [comment]
Absolutely!

`-E` is now available in the develop branch or soon in our pre-release packages. If you can test that it's working as you expect then I can plan a release. If you find any problems you can reopen this issue or create a new.

You will have to create the EDNS0 option for ECS yourself since I don't want to add more options like -X/-Y/-Z in the commit you linked, because that will eat up all options quite quickly.

If you want to create a small Python script for generating these EDNS0 option hexes, I will gladly add it to contrib :)

**Comment by Javier-Ruiz-at-Amaris** [comment]
That was super fast! Many thanks, Jerry!

I'll test it next week and report back.

**Comment by jelu** [comment]
No problem! They share the same code base so it was easy. I'm off next week
so I'll check up on this the week after.

**Comment by Javier-Ruiz-at-Amaris** [comment]
I don't find a Red Hat package for concurrencykit and compiling it is giving me a `/usr/local/bin/resperf: error while loading shared libraries: libck.so.0: cannot open shared object file: No such file or directory`
I'll have to have a second look at this.

**Comment by jelu** [comment]
What distribution and version are you using?

**Comment by Javier-Ruiz-at-Amaris** [comment]
Red Hat Enterprise Linux release 8.3 (Ootpa)

**Comment by jelu** [comment]
@Javier-Ruiz-at-Amaris We build `dnsperf` for [CentOS 8](https://copr.fedorainfracloud.org/coprs/g/dnsoarc/dnsperf/build/2097779/) and `ck-devel` is available in EPEL.

**Comment by jelu** [comment]
@Javier-Ruiz-at-Amaris Have you had time to check the fix?

**Comment by jelu** [comment]
Just added a small script to generate ECS options https://github.com/DNS-OARC/dnsperf/tree/develop/contrib/ecs-gen
