### ISSUE TITLE
how to make binary fittable with alpine distribution?

### ISSUE THREAD

**Issue by Davidrjx** [DNS-OARC/dnsperf#265]
how to build binary  from source code, fittable with alpine distribution?

**Comment by jelu** [comment]
Someone has to patch it to work with musl.

**Comment by Davidrjx** [comment]
now i have switched to glibc without attempt to patch it

**Comment by poopsicles** [comment]
note to whomever decides to patch it to work with musl: `strerror_r` returns int on non-glibc, but the logic used to detect that doesn't work rn, so building on musl would fail with gcc 14:

https://github.com/DNS-OARC/dnsperf/blob/3c452d465af669bec4eabbedc8532b10898166fc/src/strerror.c#L29-L36

```
$ ...configure, make, musl-gcc, etc.
> strerror.c: In function 'perf_strerror_r':
> strerror.c:35:12: error: returning 'int' from a function with return type 'const char *' makes pointer from integer without a cast [8;;https://gcc.gnu.org/onlinedocs/gcc-14.2.0/gcc/Warning-Options.html#index-Wint-conversion-Wint-conversion8;;]
>    35 |     return strerror_r(errnum, str, len);
>       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

alpine just [removed the check](https://gitlab.alpinelinux.org/alpine/aports/-/blob/5bd92b8f86a0bf15dddf8fa180adf14344d6cc15/testing/dnsperf/musl-perf_strerror_r.patch), because fiddling with ifdefs is a pain...but if you wanted to do things "right", i **think** you'd switch it to use [`__gnu_linux__`](https://stackoverflow.com/a/66037830) instead (that shows up for [musl on NixOS](https://github.com/NixOS/nixpkgs/issues/370498#issuecomment-2571335555))...

...and add detection of `_POSIX_C_SOURCE` to `configure.ac` (something like [this](https://stackoverflow.com/a/18240603) maybe?) so it gets emitted...but [this](https://blogs.gnome.org/tthurman/2008/11/23/_posix_c_source/#comment-383) says `_POSIX_C_SOURCE` shouldn't be used with autoconf, and [this](https://stackoverflow.com/questions/41953104/strerror-r-is-incorrectly-declared-on-alpine-linux) talks about it but gives a c++ solution...maybe it'd be easier to refactor to `strerror_l` because `strerror_r`'s [deprecated anyways](https://github.com/emscripten-core/emscripten/issues/5849#issuecomment-348740290) due to these portability problems? (not sure if that's [available everywhere](https://www.gnu.org/software/gnulib/manual/html_node/strerror_005fl.html) tho..)

(maybe just using the POSIX behaviour by default, then not doing it if `__gnu_linux__` or `_GNU_SOURCE` is present is best?)
